### ISSUE TITLE
How can I use simulation options?

### ISSUE THREAD

**Issue by SvHu** [layer8x/youtube-dl.rb#11]
I need to use newly downloaded mp3 file filename as argument in my project. For example how can I print out output filename or/and title?
With youtube-dl I can do something like this: 
```
filename =  `youtube-dl --get-filename -o  '#{folder}%(title)s.mp3' -s -x --audio-format 'mp3'   #{url}`
```
Not nicest thing to do but it works. :)
How can I do it youtube-dl.rb?

**Comment by sapslaj** [comment]
Initialize your own `YoutubeDL::Runner`.

```ruby
require 'youtube-dl.rb'

runner = YoutubeDL::Runner.new(url)
runner.options.configure do |c|
  c.get_filename = true
  c.output = "#{folder}%(title)s.mp3"
  c.simulate = true
  c.extract_audio = true
  c.audio_format = 'mp3'
end

filename = runner.run.chomp
