### ISSUE TITLE
Cocaine::ExitStatusError?

### ISSUE THREAD

**Issue by mhui** [layer8x/youtube-dl.rb#24]
This is what I'm getting when trying this library

Cocaine::ExitStatusError: Command '/Users/usercore/.rvm/gems/ruby-2.2.2/bin/youtube-dl --no-color --output 'some_file.mp4' "https://www.youtube.com/watch?v=gvdf5n-zI14"' returned 1. Expected 0

**Comment by mhui** [comment]
Turns out it was a conflict with a previous gem I had installed called youtube_dl. Lol

**Comment by sapslaj** [comment]
Yeahh.... If youtube-dl.rb (this gem) finds a youtube-dl in the system $PATH then it assumes that's the youtube-dl executable to use. Thanks for bringing my attention to the gem conflict though!

**Comment by mhui** [comment]
Thanks for your work on the gem!
