### ISSUE TITLE
Problem with get_filename

### ISSUE THREAD

**Issue by PoVa** [layer8x/youtube-dl.rb#32]
The following code
```ruby
require 'youtube-dl.rb'

video = YoutubeDL::Video.new('https://www.youtube.com/watch?v=XXXXXXXX')
video.options.configure do |c|
  c.get_filename = true
  c.output = "%(title).mp3"
  c.extract_audio = true
  c.audio_format = 'mp3'
end

video.download
video.filename
```
results in
```
/home/kristupas/.rvm/gems/ruby-2.2.4/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:91:in `run': Command '/home/kristupas/.rvm/gems/ruby-2.2.4/gems/youtube-dl.rb-0.3.0.2016.05.01/vendor/bin/youtube-dl --no-color --no-progress --print-json --get-filename --output '%(title).mp3' --extract-audio --audio-format 'mp3' "https://www.youtube.com/watch?v=_qIRtFE6aIc"' returned 1. Expected 0 (Cocaine::ExitStatusError)
Here is the command output: STDOUT:



STDERR:

ERROR: Error in output template: unsupported format character 'm' (0x6d) at index 9 (encoding: 'UTF-8')
	from /home/kristupas/.rvm/gems/ruby-2.2.4/gems/youtube-dl.rb-0.3.0.2016.05.01/lib/youtube-dl/runner.rb:62:in `run'
	from /home/kristupas/.rvm/gems/ruby-2.2.4/gems/youtube-dl.rb-0.3.0.2016.05.01/lib/youtube-dl/video.rb:39:in `download'
	from test.rb:11:in `<main>'
```
I think these two lines are causing the error, because when I comment them it works fine:
```ruby
  c.get_filename = true
  c.output = "%(title).mp3"
```
Also, I have a few questions about this gem:
  * Where can I find all available options for video?
  * Is it possible to see how large the downloaded file would be and only download it if it's not bigger than x?

**Comment by sapslaj** [comment]
```
[sapslaj@sapslaj-desktop youtube-dl.rb (master ✗)]$ youtube-dl --no-color --no-progress --print-json --get-filename --output '%(title).mp3' --extract-audio --audio-format 'mp3' "https://www.youtube.com/watch?v=gvdf5n-zI14"
ERROR: Error in output template: unsupported format character 'm' (0x6d) at index 9 (encoding: 'UTF-8')

```

This looks like it's a possible problem with `youtube-dl` itself. I'll leave this issue open and do some more investigation later tonight.

As for your questions, you can get a bunch of information from the `#information` method. If you are looking for all of the available formats, check out `video.formats`. A lot of formats will give an approximate file size. All of the information is taken straight from `--print-json.`

**Comment by sapslaj** [comment]
I think I've spotted the problem. youtube-dl requires an 's' after the parenthesis so your output template would be `%(title)s`. Also while testing this out, `get_filename` causes a bug (#34), so you'll probably want to get rid of that. `video.filename` will still work because the gem get's that information from `--print-json` when it downloads. 

Try that and report back if it works. Thanks!
