### ISSUE TITLE
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by sapslaj** [layer8x/youtube-dl.rb#44]
When installing on a Ruby that is below 2.2.2, installation fails with a failure to install activesupport

https://travis-ci.org/layer8x/youtube-dl.rb/jobs/141516789#L195

This seems to be related to [cocaine](https://github.com/thoughtbot/cocaine) which uses [climate_control](https://github.com/thoughtbot/climate_control).

EDIT: Created issue with upstream https://github.com/thoughtbot/climate_control/issues/19

**Comment by wjordan** [comment]
The temporary workaround (c2170ba1d05c872c40828ba5dcb95d8af3137bf3) breaks compatibility with up-to-date Rails/ActiveSupport projects using v`5.0.0`. An alternate workaround (that wouldn't require forking to work with Rails/ActiveSupport 5) would be to recommend projects using old versions of Ruby add a version constraint for ActiveSupport to their Gemfile, like this:

```
gem 'youtube-dl.rb'
gem 'activesupport', '< 5.0'
```

If a project is stuck on an old version of Ruby, they would need to add this constraint if any other dependency transitively referenced ActiveSupport anyway.

**Comment by sapslaj** [comment]
Thanks @wjordan. I added a [branch](https://github.com/layer8x/youtube-dl.rb/tree/activesupport-debacle) and a [PR](https://github.com/layer8x/youtube-dl.rb/pull/46). I'll merge this into master if this looks good to you.
