### ISSUE TITLE
Can't get a valid video file URL from certain videos

### ISSUE THREAD

**Issue by jcohenho** [layer8x/youtube-dl.rb#54]
Hello,
I am struggling to retrieve the correct video URL from this youtube URL:
`https://www.youtube.com/watch?v=WKziXvr6ug8`

I can download the video just fine with `youtube-dl https://www.youtube.com/watch?v=WKziXvr6ug8`, but what I really want to do is to just retrieve a valid video URL with

`youtube-dl -g --skip-download https://www.youtube.com/watch?v=WKziXvr6ug8`  but the URLs that are returned are invalid. Are there any workarounds that can help me here?

**Comment by 9mm** [comment]
so what was the problem? I have the same issue
