### ISSUE TITLE
ERROR: unable to download video info webpage: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by wonderer007** [layer8x/youtube-dl.rb#77]
## Verbose log

```
ERROR: unable to download video info webpage: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
/app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?

```

## Description

Unable to download video on server. Using [youtube-dl.rb](https://github.com/layer8x/youtube-dl.rb). Everything seems working fine in the local environment.

### Server Information
```
Linux 7b5af8abd86e 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by deepakkumar-platform** [comment]
> ## Verbose log
> 
> ```
> ERROR: unable to download video info webpage: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> /app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?
> /app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?
> ```
> 
> ## Description
> 
> Unable to download video on server. Using [youtube-dl.rb](https://github.com/layer8x/youtube-dl.rb). Everything seems working fine in the local environment.
> ### Server Information
> 
> ```
> Linux 7b5af8abd86e 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> ```

Probably API is not working

**Comment by garrettd714** [comment]
@wonderer007 what was the issue? I'm having same issue in a new docker container, when it's working fine elsewhere. ty

**Comment by wonderer007** [comment]
@garrettd714 as far as I remember it was youtube-dl version issue ( I downgraded youtube-dl version) on production to make it work
